version: "3.7"
services:  
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: ms-sql-server
    environment:           
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "k393d04.&lK$!HB04"
      MSSQL_PID: "Developer"
    ports:
      - 1433:1433
    networks:
      - proxynet
    volumes:
      # setup a place were we can load backup files            
      - /app/db/bk/:/var/app/db/bk/
networks:
  proxynet:
    # set up a shared network that can be used by other containers
    name: docker_shared_network