version: '3'

services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_sql_dev_db
      MYSQL_USER: db_dev_user
      MYSQL_PASSWORD: "hen&3l230.#hnd5"
    volumes:        
        - mysql_volume:/var/lib/mysql
    ports:
      - "9906:3306"
  web:
    # build the php image during the compose
    build: 
        context: ./
    container_name: php_web
    depends_on:
      - db
    volumes:
      # map your local php source directory to the www/html directory
      - ./src/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
    environment: 
      DB_HOST: db
      DB_NAME: my_sql_dev_db
      DB_USERNAME: db_dev_user
      DB_PASSWORD: "hen&3l230.#hnd5"
volumes:
    mysql_volume: